### ISSUE TITLE
Request on top of version 1.10

### ISSUE THREAD

**Issue by stauffenberg2020** [jonkan/EPWatch#13]
Hi Jonas,

Thanks for the price adjustment. Currently its implemented as 

(Price + Fees) * Multiplier

However, can you give us one more layer like, (So that when the price goes less than 0, Some operators still consider that as a 0 price)
**(max(0, Price) + Fees) * Multiplier**

Thanks in advance

**Comment by jonkan** [comment]
Thanks for reaching out! Should be easy enough, maybe a "Clamp negative prices to zero" on/off switch to calculate it like in your example?
