### ISSUE TITLE
Allow downloading outside of Sweden

### ISSUE THREAD

**Issue by faximan** [jonkan/EPWatch#2]
The geo restriction requires users to have a swedish app store account, which not every user interested in Sweden or its electricity prices might have.

Consider launching it globally but with a disclaimer that prices are limited to Sweden for now.

**Comment by jonkan** [comment]
Thanks Alex! I hadn't really considered that use case, I'll make it globally available with the next release.

**Comment by jonkan** [comment]
Should have been fixed by v1.1
